export const products2 = `
[
    {
      "id": 67345,
      "name": "Велосипедный фонарь",
      "brand": "Cateye",
      "type": "аксессуары",
      "price": 1200,
      "color": "Черный",
      "weight": 0.15,
      "description": "Яркий фонарь для безопасных ночных поездок.",
      "arrival_date": "2024-01-01",
      "quantity": 15,
      "img": "access.jpg"
    },
    {
      "id": 67890,
      "name": "Шоссейный велосипед 1",
      "brand": "Giant",
      "type": "велосипеды",
      "price": 51500,
      "color": "Красный",
      "size": "L",
      "weight": 9.8,
      "description": "Легкий шоссейный велосипед для дальних поездок.",
      "arrival_date": "2024-05-15",
      "quantity": 4,
      "img": "bike.jpg"
    },
    {
      "id": 54321,
      "name": "Городской велосипед 1",
      "brand": "Schwinn",
      "type": "велосипеды",
      "price": 20800,
      "color": "Синий",
      "size": "S",
      "weight": 14.2,
      "description": "Комфортный городской велосипед для ежедневных поездок.",
      "arrival_date": "2024-01-05",
      "quantity": 0,
      "img": "bike.jpg"
    },
    {
      "id": 68765,
      "name": "Велосипедный компьютер",
      "brand": "Garmin",
      "type": "аксессуары",
      "price": 6000,
      "color": "Черный",
      "weight": 0.2,
      "description": "Многофункциональный компьютер для отслеживания прогресса.",
      "arrival_date": "2024-08-20",
      "quantity": 5,
      "img": "access.jpg"
    },
    {
      "id": 11466,
      "name": "Велосипедный замок",
      "brand": "Kryptonite",
      "type": "аксессуары",
      "price": 2500,
      "color": "Черный",
      "weight": 1.2,
      "description": "Надежный замок для защиты велосипеда от кражи.",
      "arrival_date": "2024-09-10",
      "quantity": 12,
      "img": "access.jpg"
    },
    {
      "id": 40556,
      "name": "Велосипедный багажник",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 3000,
      "color": "Серый",
      "weight": 0.8,
      "description": "Прочный багажник для перевозки грузов.",
      "arrival_date": "2024-08-25",
      "quantity": 7,
      "img": "access.jpg"
    },
    {
      "id": 22335,
      "name": "Электрический велосипед 3",
      "brand": "VanMoof",
      "type": "велосипеды",
      "price": 92400,
      "color": "Серебристый",
      "size": "M",
      "weight": 18.5,
      "description": "Инновационный электрический велосипед с умными функциями.",
      "arrival_date": "2024-10-15",
      "quantity": 16,
      "img": "bike.jpg"
    },
    {
      "id": 55668,
      "name": "Складной велосипед 3",
      "brand": "Brompton",
      "type": "велосипеды",
      "price": 51200,
      "color": "Красный",
      "size": "S",
      "weight": 13.8,
      "description": "Премиальный складной велосипед для городской мобильности.",
      "arrival_date": "2024-10-20",
      "quantity": 4,
      "img": "bike.jpg"
    },
    {
      "id": 88991,
      "name": "Горный велосипед 4",
      "brand": "Yeti",
      "type": "велосипеды",
      "price": 61600,
      "color": "Синий",
      "size": "L",
      "weight": 12.7,
      "description": "Велосипед для продвинутых райдеров с ориентацией на производительность.",
      "arrival_date": "2024-10-25",
      "quantity": 19,
      "img": "bike.jpg"
    },
    {
      "id": 33446,
      "name": "Шоссейный велосипед 4",
      "brand": "Colnago",
      "type": "велосипеды",
      "price": 32200,
      "color": "Черный",
      "size": "M",
      "weight": 9.0,
      "description": "Классический шоссейный велосипед с современными технологиями.",
      "arrival_date": "2024-10-30",
      "quantity": 3,
      "img": "bike.jpg"
    },
    {
      "id": 55388,
      "name": "Велосипедный шлем с вентиляцией",
      "brand": "Giro",
      "type": "аксессуары",
      "price": 4000,
      "color": "Белый",
      "size": "L",
      "weight": 0.4,
      "description": "Шлем с системой вентиляции для комфорта в жаркую погоду.",
      "arrival_date": "2024-04-20",
      "quantity": 9,
      "img": "access.jpg"
    },
    {
      "id": 81110,
      "name": "Велосипедный флягодержатель",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 800,
      "color": "Черный",
      "weight": 0.2,
      "description": "Удобный держатель для фляги на руль.",
      "arrival_date": "2024-09-25",
      "quantity": 0,
      "img": "access.jpg"
    },
    {
      "id": 34895,
      "name": "Велосипедный насос с адаптером",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 2000,
      "color": "Серебристый",
      "weight": 0.45,
      "description": "Компактный насос с адаптером для разных типов вентилей.",
      "arrival_date": "2024-09-30",
      "quantity": 13,
      "img": "access.jpg"
    },
    {
      "id": 63868,
      "name": "Велосипедный шлем с зеркалом",
      "brand": "Giro",
      "type": "аксессуары",
      "price": 4500,
      "color": "Черный",
      "size": "M",
      "weight": 0.4,
      "description": "Шлем с встроенным зеркалом для контроля дорожной обстановки.",
      "arrival_date": "2024-10-05",
      "quantity": 6,
      "img": "access.jpg"
    },
    {
      "id": 79001,
      "name": "Велосипедный фонарь с датчиком движения",
      "brand": "Cateye",
      "type": "аксессуары",
      "price": 1500,
      "color": "Черный",
      "weight": 0.18,
      "description": "Фонарь с датчиком движения для автоматического включения.",
      "arrival_date": "2024-10-10",
      "quantity": 0,
      "img": "access.jpg"
    },
    {
      "id": 67335,
      "name": "Велосипедный насос с адаптером для автомобиля",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 2400,
      "color": "Черный",
      "weight": 0.55,
      "description": "Многофункциональный насос для велосипеда и автомобиля.",
      "arrival_date": "2024-10-15",
      "quantity": 16,
      "img": "access.jpg"
    },
    {
      "id": 78668,
      "name": "Велосипедный шлем с системой амортизации",
      "brand": "Giro",
      "type": "аксессуары",
      "price": 5000,
      "color": "Синий",
      "size": "L",
      "weight": 0.45,
      "description": "Шлем с системой амортизации для дополнительной защиты.",
      "arrival_date": "2024-10-20",
      "quantity": 4,
      "img": "access.jpg"
    },
    {
      "id": 35579,
      "name": "Велосипедный шлем с системой охлаждения",
      "brand": "Giro",
      "type": "аксессуары",
      "price": 5500,
      "color": "Белый",
      "size": "M",
      "weight": 0.5,
      "description": "Шлем с системой охлаждения для комфорта в жаркую погоду.",
      "arrival_date": "2024-11-05",
      "quantity": 2,
      "img": "access.jpg"
    },
    {
      "id": 95602,
      "name": "Велосипедный фонарь с датчиком движения и USB-зарядкой",
      "brand": "Cateye",
      "type": "аксессуары",
      "price": 2000,
      "color": "Черный",
      "weight": 0.22,
      "description": "Фонарь с датчиком движения и возможностью зарядки от USB.",
      "arrival_date": "2024-11-10",
      "quantity": 1,
      "img": "access.jpg"
    },
    {
      "id": 22396,
      "name": "Велосипедный насос с манометром, адаптером и USB-зарядкой",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 3000,
      "color": "Черный",
      "weight": 0.65,
      "description": "Многофункциональный насос с манометром, адаптером и USB-зарядкой.",
      "arrival_date": "2024-11-15",
      "quantity": 0,
      "img": "access.jpg"
    }
  ]
`;