export const products1 = `
  [
    {
      "id": 15685,
      "name": "Горный велосипед 1",
      "brand": "Trek",
      "type": "велосипеды",
      "price": 61200,
      "color": "Черный",
      "size": "M",
      "weight": 12.5,
      "description": "Прочный горный велосипед для бездорожья.",
      "arrival_date": "2024-09-01",
      "quantity": 1,
      "img": "bike.jpg"
    },
    {
      "id": 77890,
      "name": "Велосипедный насос",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 1800,
      "color": "Серебристый",
      "weight": 0.4,
      "description": "Компактный насос для поддержания давления в шинах.",
      "arrival_date": "2024-08-15",
      "quantity": 10,
      "img": "access.jpg"
    },
    {
      "id": 58321,
      "name": "Велосипедный шлем",
      "brand": "Giro",
      "type": "аксессуары",
      "price": 3500,
      "color": "Синий",
      "size": "M",
      "weight": 0.35,
      "description": "Легкий и прочный шлем для защиты головы.",
      "arrival_date": "2024-09-05",
      "quantity": 8,
      "img": "access.jpg"
    },
    {
      "id": 98765,
      "name": "Электрический велосипед 1",
      "brand": "Specialized",
      "type": "велосипеды",
      "price": 125000,
      "color": "Зеленый",
      "size": "M",
      "weight": 18.7,
      "description": "Электрический велосипед для комфортного городского передвижения.",
      "arrival_date": "2024-08-20",
      "quantity": 5,
      "img": "bike.jpg"
    },
    {
      "id": 11223,
      "name": "Складной велосипед 1",
      "brand": "Dahon",
      "type": "велосипеды",
      "price": 19450,
      "color": "Серебристый",
      "size": "S",
      "weight": 13.5,
      "description": "Компактный складной велосипед для удобного хранения и транспортировки.",
      "arrival_date": "2024-09-10",
      "quantity": 12,
      "img": "bike.jpg"
    },
    {
      "id": 44556,
      "name": "Горный велосипед 2",
      "brand": "Cannondale",
      "type": "велосипеды",
      "price": 51300,
      "color": "Оранжевый",
      "size": "L",
      "weight": 11.9,
      "description": "Прочный горный велосипед для сложных трасс.",
      "arrival_date": "2024-08-25",
      "quantity": 7,
      "img": "bike.jpg"
    },
    {
      "id": 77889,
      "name": "Шоссейный велосипед 2",
      "brand": "Cervelo",
      "type": "велосипеды",
      "price": 31800,
      "color": "Белый",
      "size": "M",
      "weight": 9.5,
      "description": "Высокопроизводительный шоссейный велосипед для соревнований.",
      "arrival_date": "2024-02-15",
      "quantity": 18,
      "img": "bike.jpg"
    },
    {
      "id": 22334,
      "name": "Городской велосипед 2",
      "brand": "Raleigh",
      "type": "велосипеды",
      "price": 23750,
      "color": "Желтый",
      "size": "M",
      "weight": 15.0,
      "description": "Стильный городской велосипед для исследования города.",
      "arrival_date": "2024-03-30",
      "quantity": 14,
      "img": "bike.jpg"
    },
    {
      "id": 55667,
      "name": "Электрический велосипед 2",
      "brand": "Brompton",
      "type": "велосипеды",
      "price": 72200,
      "color": "Черный",
      "size": "S",
      "weight": 17.8,
      "description": "Электрический велосипед с элегантным дизайном для городских поездок.",
      "arrival_date": "2024-09-20",
      "quantity": 9,
      "img": "bike.jpg"
    },
    {
      "id": 88990,
      "name": "Складной велосипед 2",
      "brand": "Tern",
      "type": "велосипеды",
      "price": 41100,
      "color": "Синий",
      "size": "M",
      "weight": 14.0,
      "description": "Универсальный складной велосипед для городских и туристических поездок.",
      "arrival_date": "2024-09-25",
      "quantity": 11,
      "img": "bike.jpg"
    },
    {
      "id": 33445,
      "name": "Горный велосипед 3",
      "brand": "Santa Cruz",
      "type": "велосипеды",
      "price": 61400,
      "color": "Зеленый",
      "size": "L",
      "weight": 12.3,
      "description": "Высококачественный горный велосипед для серьезных райдеров.",
      "arrival_date": "2024-06-30",
      "quantity": 13,
      "img": "bike.jpg"
    },
    {
      "id": 66778,
      "name": "Шоссейный велосипед 3",
      "brand": "Pinarello",
      "type": "велосипеды",
      "price": 32000,
      "color": "Красный",
      "size": "M",
      "weight": 9.2,
      "description": "Топовый шоссейный велосипед для профессиональных велосипедистов.",
      "arrival_date": "2024-10-05",
      "quantity": 6,
      "img": "bike.jpg"
    },
    {
      "id": 99001,
      "name": "Городской велосипед 3",
      "brand": "Kona",
      "type": "велосипеды",
      "price": 33850,
      "color": "Черный",
      "size": "S",
      "weight": 14.5,
      "description": "Надежный городской велосипед для ежедневного использования.",
      "arrival_date": "2024-10-10",
      "quantity": 17,
      "img": "bike.jpg"
    },
    {
      "id": 77389,
      "name": "Велосипедные перчатки",
      "brand": "Pearl Izumi",
      "type": "аксессуары",
      "price": 1500,
      "color": "Черный",
      "size": "L",
      "weight": 0.1,
      "description": "Теплые и удобные перчатки для велосипедистов.",
      "arrival_date": "2024-09-15",
      "quantity": 18,
      "img": "access.jpg"
    },
    {
      "id": 22465,
      "name": "Велосипедный насос с манометром",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 2200,
      "color": "Черный",
      "weight": 0.5,
      "description": "Компактный насос с манометром для точного контроля давления.",
      "arrival_date": "2024-08-30",
      "quantity": 14,
      "img": "access.jpg"
    },
    {
      "id": 75991,
      "name": "Велосипедный фонарь с USB-зарядкой",
      "brand": "Cateye",
      "type": "аксессуары",
      "price": 1800,
      "color": "Черный",
      "weight": 0.2,
      "description": "Фонарь с возможностью зарядки от USB.",
      "arrival_date": "2024-10-25",
      "quantity": 19,
      "img": "access.jpg"
    },
    {
      "id": 37896,
      "name": "Велосипедный насос с манометром и адаптером",
      "brand": "Topeak",
      "type": "аксессуары",
      "price": 2600,
      "color": "Серебристый",
      "weight": 0.6,
      "description": "Компактный насос с манометром и адаптером для разных вентилей.",
      "arrival_date": "2024-10-30",
      "quantity": 3,
      "img": "access.jpg"
    },
    {
      "id": 66779,
      "name": "Городской велосипед 4",
      "brand": "Electra",
      "type": "велосипеды",
      "price": 29900,
      "color": "Зеленый",
      "size": "M",
      "weight": 15.2,
      "description": "Стильный и комфортный городской велосипед.",
      "arrival_date": "2024-11-05",
      "quantity": 2,
      "img": "bike.jpg"
    },
    {
      "id": 99002,
      "name": "Электрический велосипед 4",
      "brand": "Gocycle",
      "type": "велосипеды",
      "price": 82600,
      "color": "Желтый",
      "size": "S",
      "weight": 19.0,
      "description": "Передовой электрический велосипед с уникальным дизайном.",
      "arrival_date": "2024-11-10",
      "quantity": 1,
      "img": "bike.jpg"
    },
    {
      "id": 63868,
      "name": "Велосипедный шлем с зеркалом",
      "brand": "Giro",
      "type": "аксессуары",
      "price": 4500,
      "color": "Черный",
      "size": "M",
      "weight": 0.4,
      "description": "Шлем с встроенным зеркалом для контроля дорожной обстановки.",
      "arrival_date": "2024-10-05",
      "quantity": 6,
      "img": "access.jpg"
    }
  ]
`;